name: Upload Jekyll site to s3 bucket

on:
  pull_request:
    types: [closed]
    branches:
        - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

    # Step 2: Set up Ruby environment (Jekyll requires Ruby)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
    
      # Step 3: Install Jekyll dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
    
      # Step 4: Build the Jekyll site
      - name: Build the site
        run: bundle exec jekyll build
    
      # Step 5: Sync the `_site` folder with S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Replace with your region
        run: |
          aws s3 sync ./_site s3://cloudresumeweb --acl public-read --delete
